-- Insert subjects for SSS 1 and SSS 2 grade levels
INSERT INTO public.subject_configurations (grade_level, subject_name, display_order, is_active) VALUES
-- SSS 1 subjects
('SSS 1', 'English Language', 1, true),
('SSS 1', 'Mathematics', 2, true),
('SSS 1', 'Civic Education', 3, true),
('SSS 1', 'Marketing', 4, true),
('SSS 1', 'Physics', 5, true),
('SSS 1', 'Computer Studies', 6, true),
('SSS 1', 'Chemistry', 7, true),
('SSS 1', 'Biology', 8, true),
('SSS 1', 'Agriculture', 9, true),
('SSS 1', 'Further Mathematics', 10, true),
('SSS 1', 'Government', 11, true),
('SSS 1', 'Economics', 12, true),
('SSS 1', 'Religion (CRS)', 13, true),
('SSS 1', 'Religion (IRS)', 14, true),
('SSS 1', 'Geography', 15, true),
('SSS 1', 'Commerce', 16, true),
('SSS 1', 'Financial Accounting', 17, true),
('SSS 1', 'Literature in English', 18, true),
('SSS 1', 'Hausa', 19, true),
('SSS 1', 'French', 20, true),
('SSS 1', 'Food and Nutrition', 21, true),
('SSS 1', 'Technical Drawing', 22, true),
('SSS 1', 'Visual Art', 23, true),
('SSS 1', 'History', 24, true),
('SSS 1', 'Data Processing', 25, true),
('SSS 1', 'Arabic Studies', 26, true),

-- SSS 2 subjects
('SSS 2', 'English Language', 1, true),
('SSS 2', 'Mathematics', 2, true),
('SSS 2', 'Civic Education', 3, true),
('SSS 2', 'Marketing', 4, true),
('SSS 2', 'Physics', 5, true),
('SSS 2', 'Computer Studies', 6, true),
('SSS 2', 'Chemistry', 7, true),
('SSS 2', 'Biology', 8, true),
('SSS 2', 'Agriculture', 9, true),
('SSS 2', 'Further Mathematics', 10, true),
('SSS 2', 'Government', 11, true),
('SSS 2', 'Economics', 12, true),
('SSS 2', 'Religion (CRS)', 13, true),
('SSS 2', 'Religion (IRS)', 14, true),
('SSS 2', 'Geography', 15, true),
('SSS 2', 'Commerce', 16, true),
('SSS 2', 'Financial Accounting', 17, true),
('SSS 2', 'Literature in English', 18, true),
('SSS 2', 'Hausa', 19, true),
('SSS 2', 'French', 20, true),
('SSS 2', 'Food and Nutrition', 21, true),
('SSS 2', 'Technical Drawing', 22, true),
('SSS 2', 'Visual Art', 23, true),
('SSS 2', 'History', 24, true),
('SSS 2', 'Data Processing', 25, true),
('SSS 2', 'Arabic Studies', 26, true);