// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzrlehhmzcrsgqyzopfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6cmxlaGhtemNyc2dxeXpvcGZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyOTk2MDEsImV4cCI6MjA2OTg3NTYwMX0.Yr1_jiZtDKMIW_e3Utq_6oGb1eUHE8BHw09YAkWBfTc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});